Json reader test
googleinterns/droid-jump pull request #27
Opened 2020-08-19 08:52 UTC by Daniel-ND

2020-08-19 16:42 UTC, saimonsaret requested changes

2020-08-19 16:42 UTC, saimonsaret commented on app/src/androidTest/java/com/google/droidjump/leveldata/JSONReaderTest.java
> +    public void getJSONObjectFromResource() throws JSONException {
A good test for a general case. Can you try testing the edge cases as well? For example, when timeline array is empty. Also, what about finite and infinite levels?

2020-08-20 11:53 UTC, redls commented on app/src/androidTest/java/com/google/droidjump/leveldata/JSONReaderTest.java
> +
remove newline.

2020-08-26 09:11 UTC, saimonsaret approved these changes

2020-08-26 09:11 UTC, saimonsaret commented on app/src/androidTest/java/com/google/droidjump/leveldata/JSONReaderTest.java
> +    public void getJSONObjectFromResource() throws JSONException {
It is OK in this case, you could leave it like that.

2020-08-26 09:59 UTC, merged